In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data = pd.read_csv('final_data.csv')

In [3]:
data.head()

Unnamed: 0   LONGITUDE   LATITUDE  SPD      LEN    ACC      VOL  F85th  \
0           0 -121.803753  37.227881   35   3200.0   18.0   8100.0   40.0   
1           1 -121.791060  37.225223   25   3362.0    4.0   2550.0   29.0   
2           2 -121.862273  37.341412   25   4400.0   42.0   7550.0   29.5   
3           3 -121.900218  37.331962   25   1580.0    5.0   3000.0   29.5   
4           4 -121.860729  37.358019   40  13100.0  281.0  29500.0   41.3   

   LOCAL  F50th  Precip  Air max  min   obs  hour  Accident  
0      0   36.0    0.00       83   57  70.0  17.0         0  
1      0   26.0    0.07       67   47  57.0   7.0         0  
2      0   26.0    0.00       82   59  70.5   0.0         0  
3      0   26.0    0.02       69   49  59.0  19.0         0  
4      0   37.3    0.07       59   42  50.5   3.0         0

In [4]:
data.shape

(4352, 16)

In [5]:
for cols in data.columns:
    print(cols)

Unnamed: 0
LONGITUDE
LATITUDE
SPD
LEN
ACC
VOL
F85th
LOCAL
F50th
Precip
Air max
min
obs
hour
Accident


In [6]:
data.drop('Unnamed: 0', inplace=True, axis=1)

In [7]:
data

LONGITUDE   LATITUDE  SPD      LEN    ACC      VOL  F85th  LOCAL  \
0    -121.803753  37.227881   35   3200.0   18.0   8100.0   40.0      0   
1    -121.791060  37.225223   25   3362.0    4.0   2550.0   29.0      0   
2    -121.862273  37.341412   25   4400.0   42.0   7550.0   29.5      0   
3    -121.900218  37.331962   25   1580.0    5.0   3000.0   29.5      0   
4    -121.860729  37.358019   40  13100.0  281.0  29500.0   41.3      0   
...          ...        ...  ...      ...    ...      ...    ...    ...   
4347 -121.882064  37.221661   35   8750.0   30.0  10800.0   39.3      0   
4348 -121.871737  37.396813   35   7300.0   28.0  14300.0   39.5      0   
4349 -121.791719  37.314021   40  10990.0   71.0  25800.0   43.7      0   
4350 -121.891325  37.307313   25   3600.0   21.0  11700.0   29.5      0   
4351 -121.797626  37.329070   25   3900.0   11.0   1480.0   34.0      1   

      F50th  Precip  Air max  min   obs  hour  Accident  
0      36.0    0.00       83   57  70.0  17.0         0  
1      26.0    0.07       67   47  57.0   7.0         0  
2      26.0    0.00       82   59  70.5   0.0         0  
3      26.0    0.02       69   49  59.0  19.0         0  
4      37.3    0.07       59   42  50.5   3.0         0  
...     ...     ...      ...  ...   ...   ...       ...  
4347   36.0    0.06       57   41  49.0  11.0         0  
4348   35.5    0.12       58   42  50.0   5.0         0  
4349   39.3    0.01       76   52  64.0  12.0         0  
4350   26.5    0.02       69   49  59.0  23.0         0  
4351   25.0    0.04       74   53  63.5   7.0         0  

[4352 rows x 15 columns]

In [8]:
corr = data.corr()
corr.style.background_gradient(cmap='coolwarm')

In [9]:
corr_target = abs(corr["Accident"])
relevant_features = corr_target[corr_target>0]
relevant_features

LONGITUDE    0.074499
LATITUDE     0.030319
SPD          0.078078
LEN          0.048758
ACC          0.079725
VOL          0.075766
F85th        0.065605
LOCAL        0.086541
F50th        0.077074
Precip       0.010966
Air max      0.012667
min          0.012824
obs          0.012783
hour         0.095007
Accident     1.000000
Name: Accident, dtype: float64

In [10]:
for cols in data.columns:
    if cols not in relevant_features:
        print(cols)
        data.drop(f'{cols}', axis=1, inplace=True)

In [11]:
data.head()

LONGITUDE   LATITUDE  SPD      LEN    ACC      VOL  F85th  LOCAL  F50th  \
0 -121.803753  37.227881   35   3200.0   18.0   8100.0   40.0      0   36.0   
1 -121.791060  37.225223   25   3362.0    4.0   2550.0   29.0      0   26.0   
2 -121.862273  37.341412   25   4400.0   42.0   7550.0   29.5      0   26.0   
3 -121.900218  37.331962   25   1580.0    5.0   3000.0   29.5      0   26.0   
4 -121.860729  37.358019   40  13100.0  281.0  29500.0   41.3      0   37.3   

   Precip  Air max  min   obs  hour  Accident  
0    0.00       83   57  70.0  17.0         0  
1    0.07       67   47  57.0   7.0         0  
2    0.00       82   59  70.5   0.0         0  
3    0.02       69   49  59.0  19.0         0  
4    0.07       59   42  50.5   3.0         0

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X = data.drop('Accident', axis=1)

In [14]:
y = data['Accident']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [13]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
dtree = DecisionTreeClassifier()

In [18]:
dtree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [19]:
predictions = dtree.predict(X_test)

In [14]:
from sklearn.metrics import classification_report,confusion_matrix

In [21]:
print(confusion_matrix(y_test,predictions))

[[894 157]
 [172  83]]


In [22]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.84      0.85      0.84      1051
           1       0.35      0.33      0.34       255

    accuracy                           0.75      1306
   macro avg       0.59      0.59      0.59      1306
weighted avg       0.74      0.75      0.75      1306



In [23]:
lst = []
for val in y_test:
    lst.append(val)

In [24]:
score = 0
for i in range(len(predictions)):
    if predictions[i] == lst[i]:
        score += 1

In [25]:
print(score/len(predictions)*100)

74.80857580398163


In [15]:
def predict(data):
    X = data.drop('Accident', axis=1)
    y = data['Accident']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
    dtree = DecisionTreeClassifier()
    dtree.fit(X_train, y_train)
    predictions = dtree.predict(X_test)
    print(confusion_matrix(y_test,predictions))
    print(classification_report(y_test,predictions))
    lst = []
    for val in y_test:
        lst.append(val)
    score = 0
    for i in range(len(predictions)):
        if predictions[i] == lst[i]:
            score += 1
    print(score/len(predictions)*100)

In [16]:
predict(data)

[[886 181]
 [155  84]]
              precision    recall  f1-score   support

           0       0.85      0.83      0.84      1067
           1       0.32      0.35      0.33       239

    accuracy                           0.74      1306
   macro avg       0.58      0.59      0.59      1306
weighted avg       0.75      0.74      0.75      1306

74.27258805513017


In [17]:
for col in data.columns:
    if col != 'Accident':
        data[col] = data[col]/data[col].mean()

In [18]:
data

LONGITUDE  LATITUDE       SPD       LEN       ACC       VOL     F85th  \
0      0.999409  0.997846  1.070603  0.626969  0.510868  0.749049  1.099830   
1      0.999305  0.997774  0.764716  0.658709  0.113526  0.235812  0.797377   
2      0.999890  1.000889  0.764716  0.862083  1.192026  0.698187  0.811125   
3      1.000201  1.000635  0.764716  0.309566  0.141908  0.277425  0.811125   
4      0.999877  1.001334  1.223546  2.566655  7.975218  2.728017  1.135575   
...         ...       ...       ...       ...       ...       ...       ...   
4347   1.000052  0.997679  1.070603  1.714369  0.851447  0.998732  1.080583   
4348   0.999967  1.002374  1.070603  1.430273  0.794684  1.322394  1.086082   
4349   0.999311  1.000154  1.223546  2.153247  2.015091  2.385859  1.201564   
4350   1.000128  0.999975  0.764716  0.705340  0.596013  1.081959  0.811125   
4351   0.999359  1.000558  0.764716  0.764119  0.312197  0.136863  0.934856   

          LOCAL     F50th    Precip   Air max       min       obs      hour  \
0      0.000000  1.113024  0.000000  1.163269  1.125670  1.147662  1.419657   
1      0.000000  0.803850  1.555794  0.939024  0.928184  0.934525  0.584565   
2      0.000000  0.803850  0.000000  1.149254  1.165168  1.155860  0.000000   
3      0.000000  0.803850  0.444513  0.967055  0.967682  0.967315  1.586675   
4      0.000000  1.153216  1.555794  0.826902  0.829441  0.827956  0.250528   
...         ...       ...       ...       ...       ...       ...       ...   
4347   0.000000  1.113024  1.333538  0.798872  0.809693  0.803363  0.918602   
4348   0.000000  1.097565  2.667075  0.812887  0.829441  0.819759  0.417546   
4349   0.000000  1.215051  0.222256  1.065162  1.026927  1.049291  1.002111   
4350   0.000000  0.819309  0.444513  0.967055  0.967682  0.967315  1.920712   
4351  13.815873  0.772933  0.889025  1.037132  1.046676  1.041093  0.584565   

      Accident  
0            0  
1            0  
2            0  
3            0  
4            0  
...        ...  
4347         0  
4348         0  
4349         0  
4350         0  
4351         0  

[4352 rows x 15 columns]

In [19]:
predict(data)

[[919 142]
 [157  88]]
              precision    recall  f1-score   support

           0       0.85      0.87      0.86      1061
           1       0.38      0.36      0.37       245

    accuracy                           0.77      1306
   macro avg       0.62      0.61      0.62      1306
weighted avg       0.77      0.77      0.77      1306

77.10566615620215


In [23]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
clf = RandomForestClassifier(n_estimators=100, max_depth=2,random_state=0)

In [22]:
clf.fit(X_train, y_train)

NameError: name 'X_train' is not defined

In [35]:
def predict2(data):
    X = data.drop('Accident', axis=1)
    y = data['Accident']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
    clf = RandomForestClassifier(n_estimators=100, max_depth=3,random_state=0)
    clf.fit(X_train, y_train)
    predictions = clf.predict(X_test)
    print(confusion_matrix(y_test,predictions))
    print(classification_report(y_test,predictions))
    lst = []
    for val in y_test:
        lst.append(val)
    score = 0
    for i in range(len(predictions)):
        if predictions[i] == lst[i]:
            score += 1
    print(score/len(predictions)*100)

In [41]:
predict2(data)

[[1039    0]
 [ 267    0]]
              precision    recall  f1-score   support

           0       0.80      1.00      0.89      1039
           1       0.00      0.00      0.00       267

    accuracy                           0.80      1306
   macro avg       0.40      0.50      0.44      1306
weighted avg       0.63      0.80      0.70      1306

79.55589586523737


/Users/darthvader/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
